aliases:
  - &restore-yarn-cache-10
    keys:
      - v5-yarn-10-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v5-yarn-10-{{ .Branch }}-

  - &save-yarn-cache-10
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v5-yarn-10-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &restore-yarn-cache-12
    keys:
      - v5-yarn-12-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v5-yarn-12-{{ .Branch }}-

  - &save-yarn-cache-12
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v5-yarn-12-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &yarn |
    yarn install --non-interactive --cache-folder ~/.cache/yarn

  - &lint
    working_directory: ~/neo-one-playground
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache-8
      - run: *yarn
      - save-cache: *save-yarn-cache-8
      - run:
          name: Prettier
          command: yarn nit
          when: always
      - run:
          name: Typescript
          command: yarn tsc
          when: always
      - run:
          name: Lint
          command: yarn lint
          when: always

  - &test10
    working_directory: ~/neo-one-playground
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache-810
      - run: *yarn
      - save-cache: *save-yarn-cache-10
      - run:
          name: Test
          command: yarn test --ci -w 1

  - &cypress10
    working_directory: ~/neo-one-playground
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache-10
      - run: *yarn
      - save-cache: *save-yarn-cache-10
      - run:
          name: Test
          command: yarn test:cypress
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


node10: &node10
  docker:
    - image: neotracker/neo-one-circleci-node@sha256:0f047d3662ad72b75e9550e41b22a2be0bf7fa8ee6563b65272b5af966b07f20

node12: &node12
  docker:
    - image: neotracker/neo-one-circleci-node@sha256:6f76ab22882896c057d9d805955892f1dee26bb1a4257a6d095d07d617aa4d5c

chrome: &chrome69
  docker:
    - image: cypress/browsers:chrome69

version: 2
jobs:
  test10:
    <<: *node10
    <<: *test10
  cypress10:
    <<: *chrome69
    <<: *cypress10

  lint:
    <<: *node10
    <<: *lint

workflows:
  version: 2
  test10:
    jobs:
      - lint
      - test10
      - cypress10
